# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mgmt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mgmt.proto',
  package='mgmt',
  syntax='proto3',
  serialized_options=b'Z\032github.com/DCSO/fever/mgmt',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmgmt.proto\x12\x04mgmt\x1a\x1bgoogle/protobuf/empty.proto\"\x7f\n\x15MgmtBloomInfoResponse\x12\x11\n\thas_bloom\x18\x01 \x01(\x08\x12\x10\n\x08\x63\x61pacity\x18\x02 \x01(\x04\x12\x10\n\x08\x65lements\x18\x03 \x01(\x04\x12\x0c\n\x04\x62its\x18\x04 \x01(\x04\x12\x11\n\thashfuncs\x18\x05 \x01(\x04\x12\x0e\n\x06\x66pprob\x18\x06 \x01(\x01\"!\n\x10MgmtAliveRequest\x12\r\n\x05\x61live\x18\x01 \x01(\t\"!\n\x11MgmtAliveResponse\x12\x0c\n\x04\x65\x63ho\x18\x01 \x01(\t\"\"\n\x13MgmtBloomAddRequest\x12\x0b\n\x03ioc\x18\x01 \x01(\t\"%\n\x14MgmtBloomAddResponse\x12\r\n\x05\x61\x64\x64\x65\x64\x18\x01 \x01(\x04\x32\xca\x02\n\x0bMgmtService\x12\x38\n\x05\x41live\x12\x16.mgmt.MgmtAliveRequest\x1a\x17.mgmt.MgmtAliveResponse\x12@\n\tBloomInfo\x12\x16.google.protobuf.Empty\x1a\x1b.mgmt.MgmtBloomInfoResponse\x12\x43\n\x08\x42loomAdd\x12\x19.mgmt.MgmtBloomAddRequest\x1a\x1a.mgmt.MgmtBloomAddResponse(\x01\x12;\n\tBloomSave\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n\x0b\x42loomReload\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyB\x1cZ\x1agithub.com/DCSO/fever/mgmtb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_MGMTBLOOMINFORESPONSE = _descriptor.Descriptor(
  name='MgmtBloomInfoResponse',
  full_name='mgmt.MgmtBloomInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_bloom', full_name='mgmt.MgmtBloomInfoResponse.has_bloom', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='capacity', full_name='mgmt.MgmtBloomInfoResponse.capacity', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='elements', full_name='mgmt.MgmtBloomInfoResponse.elements', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bits', full_name='mgmt.MgmtBloomInfoResponse.bits', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hashfuncs', full_name='mgmt.MgmtBloomInfoResponse.hashfuncs', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fpprob', full_name='mgmt.MgmtBloomInfoResponse.fpprob', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=176,
)


_MGMTALIVEREQUEST = _descriptor.Descriptor(
  name='MgmtAliveRequest',
  full_name='mgmt.MgmtAliveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alive', full_name='mgmt.MgmtAliveRequest.alive', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=211,
)


_MGMTALIVERESPONSE = _descriptor.Descriptor(
  name='MgmtAliveResponse',
  full_name='mgmt.MgmtAliveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='echo', full_name='mgmt.MgmtAliveResponse.echo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=246,
)


_MGMTBLOOMADDREQUEST = _descriptor.Descriptor(
  name='MgmtBloomAddRequest',
  full_name='mgmt.MgmtBloomAddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ioc', full_name='mgmt.MgmtBloomAddRequest.ioc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=282,
)


_MGMTBLOOMADDRESPONSE = _descriptor.Descriptor(
  name='MgmtBloomAddResponse',
  full_name='mgmt.MgmtBloomAddResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='added', full_name='mgmt.MgmtBloomAddResponse.added', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=321,
)

DESCRIPTOR.message_types_by_name['MgmtBloomInfoResponse'] = _MGMTBLOOMINFORESPONSE
DESCRIPTOR.message_types_by_name['MgmtAliveRequest'] = _MGMTALIVEREQUEST
DESCRIPTOR.message_types_by_name['MgmtAliveResponse'] = _MGMTALIVERESPONSE
DESCRIPTOR.message_types_by_name['MgmtBloomAddRequest'] = _MGMTBLOOMADDREQUEST
DESCRIPTOR.message_types_by_name['MgmtBloomAddResponse'] = _MGMTBLOOMADDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MgmtBloomInfoResponse = _reflection.GeneratedProtocolMessageType('MgmtBloomInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _MGMTBLOOMINFORESPONSE,
  '__module__' : 'mgmt_pb2'
  # @@protoc_insertion_point(class_scope:mgmt.MgmtBloomInfoResponse)
  })
_sym_db.RegisterMessage(MgmtBloomInfoResponse)

MgmtAliveRequest = _reflection.GeneratedProtocolMessageType('MgmtAliveRequest', (_message.Message,), {
  'DESCRIPTOR' : _MGMTALIVEREQUEST,
  '__module__' : 'mgmt_pb2'
  # @@protoc_insertion_point(class_scope:mgmt.MgmtAliveRequest)
  })
_sym_db.RegisterMessage(MgmtAliveRequest)

MgmtAliveResponse = _reflection.GeneratedProtocolMessageType('MgmtAliveResponse', (_message.Message,), {
  'DESCRIPTOR' : _MGMTALIVERESPONSE,
  '__module__' : 'mgmt_pb2'
  # @@protoc_insertion_point(class_scope:mgmt.MgmtAliveResponse)
  })
_sym_db.RegisterMessage(MgmtAliveResponse)

MgmtBloomAddRequest = _reflection.GeneratedProtocolMessageType('MgmtBloomAddRequest', (_message.Message,), {
  'DESCRIPTOR' : _MGMTBLOOMADDREQUEST,
  '__module__' : 'mgmt_pb2'
  # @@protoc_insertion_point(class_scope:mgmt.MgmtBloomAddRequest)
  })
_sym_db.RegisterMessage(MgmtBloomAddRequest)

MgmtBloomAddResponse = _reflection.GeneratedProtocolMessageType('MgmtBloomAddResponse', (_message.Message,), {
  'DESCRIPTOR' : _MGMTBLOOMADDRESPONSE,
  '__module__' : 'mgmt_pb2'
  # @@protoc_insertion_point(class_scope:mgmt.MgmtBloomAddResponse)
  })
_sym_db.RegisterMessage(MgmtBloomAddResponse)


DESCRIPTOR._options = None

_MGMTSERVICE = _descriptor.ServiceDescriptor(
  name='MgmtService',
  full_name='mgmt.MgmtService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=324,
  serialized_end=654,
  methods=[
  _descriptor.MethodDescriptor(
    name='Alive',
    full_name='mgmt.MgmtService.Alive',
    index=0,
    containing_service=None,
    input_type=_MGMTALIVEREQUEST,
    output_type=_MGMTALIVERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BloomInfo',
    full_name='mgmt.MgmtService.BloomInfo',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_MGMTBLOOMINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BloomAdd',
    full_name='mgmt.MgmtService.BloomAdd',
    index=2,
    containing_service=None,
    input_type=_MGMTBLOOMADDREQUEST,
    output_type=_MGMTBLOOMADDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BloomSave',
    full_name='mgmt.MgmtService.BloomSave',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BloomReload',
    full_name='mgmt.MgmtService.BloomReload',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MGMTSERVICE)

DESCRIPTOR.services_by_name['MgmtService'] = _MGMTSERVICE

# @@protoc_insertion_point(module_scope)
